version: '3.1'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
    volumes:
      - ./mysql-data:/var/lib/mysql
